// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBunNju-JnuHdjXQIm8RmTP0cjExtgsitk',
    appId: '1:1070731958015:web:72f8c1cad5f70f80ed1eca',
    messagingSenderId: '1070731958015',
    projectId: 'chat-app-a746d',
    authDomain: 'chat-app-a746d.firebaseapp.com',
    databaseURL: 'https://chat-app-a746d-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-a746d.firebasestorage.app',
    measurementId: 'G-FWZLF6MQXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBbLWZ8gdDeCslMYReMNK8a-kQoxi8xYs',
    appId: '1:1070731958015:android:36888ed26bf29a0ced1eca',
    messagingSenderId: '1070731958015',
    projectId: 'chat-app-a746d',
    databaseURL: 'https://chat-app-a746d-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-a746d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXE-Jej1KR1EdUlCq3LquaeCkdpTCmcgU',
    appId: '1:1070731958015:ios:a4f29cfe1128bd2fed1eca',
    messagingSenderId: '1070731958015',
    projectId: 'chat-app-a746d',
    databaseURL: 'https://chat-app-a746d-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-a746d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXE-Jej1KR1EdUlCq3LquaeCkdpTCmcgU',
    appId: '1:1070731958015:ios:a4f29cfe1128bd2fed1eca',
    messagingSenderId: '1070731958015',
    projectId: 'chat-app-a746d',
    databaseURL: 'https://chat-app-a746d-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-a746d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBunNju-JnuHdjXQIm8RmTP0cjExtgsitk',
    appId: '1:1070731958015:web:b69d124610114b06ed1eca',
    messagingSenderId: '1070731958015',
    projectId: 'chat-app-a746d',
    authDomain: 'chat-app-a746d.firebaseapp.com',
    databaseURL: 'https://chat-app-a746d-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-a746d.firebasestorage.app',
    measurementId: 'G-GENP020TXQ',
  );
}
